# GNU Make solution makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MemoryPool_config = debug
endif
ifeq ($(config),release)
  MemoryPool_config = release
endif

PROJECTS := MemoryPool

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

MemoryPool:
ifneq (,$(MemoryPool_config))
	@echo "==== Building MemoryPool ($(MemoryPool_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(MemoryPool_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MemoryPool"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
